#pragma once

#include <unordered_map>
#include <vector>

enum SpecKeys
{
  SPECKEY_NONE,
  SPECKEY_1,
  SPECKEY_2,
  SPECKEY_3,
  SPECKEY_4,
  SPECKEY_5,
  SPECKEY_6,
  SPECKEY_7,
  SPECKEY_8,
  SPECKEY_9,
  SPECKEY_0,
  SPECKEY_Q,
  SPECKEY_W,
  SPECKEY_E,
  SPECKEY_R,
  SPECKEY_T,
  SPECKEY_Y,
  SPECKEY_U,
  SPECKEY_I,
  SPECKEY_O,
  SPECKEY_P,
  SPECKEY_A,
  SPECKEY_S,
  SPECKEY_D,
  SPECKEY_F,
  SPECKEY_G,
  SPECKEY_H,
  SPECKEY_J,
  SPECKEY_K,
  SPECKEY_L,
  SPECKEY_ENTER,
  SPECKEY_SHIFT,
  SPECKEY_Z,
  SPECKEY_X,
  SPECKEY_C,
  SPECKEY_V,
  SPECKEY_B,
  SPECKEY_N,
  SPECKEY_M,
  SPECKEY_SYMB,
  SPECKEY_SPACE,
  // indicates that everything above is not a normal key
  SPECKEY_MAX_NORMAL,
  // joystick keys
  JOYK_UP,
  JOYK_DOWN,
  JOYK_LEFT,
  JOYK_RIGHT,
  JOYK_FIRE,
  // special pseudo keys
  SPECKEY_DEL,
  SPECKEY_BREAK,
  // special keys for the emulator
  SPECKEY_MENU,
};

const std::unordered_map<SpecKeys, char> specKeyToLetter = {
  { SPECKEY_0, '0' },
  { SPECKEY_1, '1' },
  { SPECKEY_2, '2' },
  { SPECKEY_3, '3' },
  { SPECKEY_4, '4' },
  { SPECKEY_5, '5' },
  { SPECKEY_6, '6' },
  { SPECKEY_7, '7' },
  { SPECKEY_8, '8' },
  { SPECKEY_9, '9' },
  { SPECKEY_A, 'A' },
  { SPECKEY_B, 'B' },
  { SPECKEY_C, 'C' },
  { SPECKEY_D, 'D' },
  { SPECKEY_E, 'E' },
  { SPECKEY_F, 'F' },
  { SPECKEY_G, 'G' },
  { SPECKEY_H, 'H' },
  { SPECKEY_I, 'I' },
  { SPECKEY_J, 'J' },
  { SPECKEY_K, 'K' },
  { SPECKEY_L, 'L' },
  { SPECKEY_M, 'M' },
  { SPECKEY_N, 'N' },
  { SPECKEY_O, 'O' },
  { SPECKEY_P, 'P' },
  { SPECKEY_Q, 'Q' },
  { SPECKEY_R, 'R' },
  { SPECKEY_S, 'S' },
  { SPECKEY_T, 'T' },
  { SPECKEY_U, 'U' },
  { SPECKEY_V, 'V' },
  { SPECKEY_W, 'W' },
  { SPECKEY_X, 'X' },
  { SPECKEY_Y, 'Y' },
  { SPECKEY_Z, 'Z' },
};

// map letters to the SpecKeys enum
const std::unordered_map<char, std::vector<SpecKeys>> letterToSpecKeys = {
  { '0', { SPECKEY_0 } },
  { '1', { SPECKEY_1 } },
  { '2', { SPECKEY_2 } },
  { '3', { SPECKEY_3 } },
  { '4', { SPECKEY_4 } },
  { '5', { SPECKEY_5 } },
  { '6', { SPECKEY_6 } },
  { '7', { SPECKEY_7 } },
  { '8', { SPECKEY_8 } },
  { '9', { SPECKEY_9 } },
  { 'A', { SPECKEY_A } },
  { 'B', { SPECKEY_B } },
  { 'C', { SPECKEY_C } },
  { 'D', { SPECKEY_D } },
  { 'E', { SPECKEY_E } },
  { 'F', { SPECKEY_F } },
  { 'G', { SPECKEY_G } },
  { 'H', { SPECKEY_H } },
  { 'I', { SPECKEY_I } },
  { 'J', { SPECKEY_J } },
  { 'K', { SPECKEY_K } },
  { 'L', { SPECKEY_L } },
  { 'M', { SPECKEY_M } },
  { 'N', { SPECKEY_N } },
  { 'O', { SPECKEY_O } },
  { 'P', { SPECKEY_P } },
  { 'Q', { SPECKEY_Q } },
  { 'R', { SPECKEY_R } },
  { 'S', { SPECKEY_S } },
  { 'T', { SPECKEY_T } },
  { 'U', { SPECKEY_U } },
  { 'V', { SPECKEY_V } },
  { 'W', { SPECKEY_W } },
  { 'X', { SPECKEY_X } },
  { 'Y', { SPECKEY_Y } },
  { 'Z', { SPECKEY_Z } },
  { 'a', { SPECKEY_A } },
  { 'b', { SPECKEY_B } },
  { 'c', { SPECKEY_C } },
  { 'd', { SPECKEY_D } },
  { 'e', { SPECKEY_E } },
  { 'f', { SPECKEY_F } },
  { 'g', { SPECKEY_G } },
  { 'h', { SPECKEY_H } },
  { 'i', { SPECKEY_I } },
  { 'j', { SPECKEY_J } },
  { 'k', { SPECKEY_K } },
  { 'l', { SPECKEY_L } },
  { 'm', { SPECKEY_M } },
  { 'n', { SPECKEY_N } },
  { 'o', { SPECKEY_O } },
  { 'p', { SPECKEY_P } },
  { 'q', { SPECKEY_Q } },
  { 'r', { SPECKEY_R } },
  { 's', { SPECKEY_S } },
  { 't', { SPECKEY_T } },
  { 'u', { SPECKEY_U } },
  { 'v', { SPECKEY_V } },
  { 'w', { SPECKEY_W } },
  { 'x', { SPECKEY_X } },
  { 'y', { SPECKEY_Y } },
  { 'z', { SPECKEY_Z } },
  { ' ', { SPECKEY_SPACE } },
  { 0x0d, { SPECKEY_ENTER } },
  { '!', { SPECKEY_1, SPECKEY_SYMB } },
  { '@', { SPECKEY_2, SPECKEY_SYMB } },
  { '#', { SPECKEY_3, SPECKEY_SYMB } },
  { '$', { SPECKEY_4, SPECKEY_SYMB } },
  { '%', { SPECKEY_5, SPECKEY_SYMB } },
  { '&', { SPECKEY_6, SPECKEY_SYMB } },
  { '\'', { SPECKEY_7, SPECKEY_SYMB } },
  { '(', { SPECKEY_8, SPECKEY_SYMB } },
  { ')', { SPECKEY_9, SPECKEY_SYMB } },
  { '_', { SPECKEY_0, SPECKEY_SYMB } },
  { '<', { SPECKEY_R, SPECKEY_SYMB } },
  { '>', { SPECKEY_T, SPECKEY_SYMB } },
  { ';', { SPECKEY_O, SPECKEY_SYMB } },
  { '"', { SPECKEY_P, SPECKEY_SYMB } },
  { '-', { SPECKEY_J, SPECKEY_SYMB } },
  { '+', { SPECKEY_K, SPECKEY_SYMB } },
  { '=', { SPECKEY_L, SPECKEY_SYMB } },
  { ':', { SPECKEY_Z, SPECKEY_SYMB } },
  { '$', { SPECKEY_X, SPECKEY_SYMB } },
  { '?', { SPECKEY_C, SPECKEY_SYMB } },
  { '/', { SPECKEY_V, SPECKEY_SYMB } },
  { '*', { SPECKEY_B, SPECKEY_SYMB } },
  { ',', { SPECKEY_N, SPECKEY_SYMB } },
  { '.', { SPECKEY_M, SPECKEY_SYMB } },
};